#!/bin/bash
#
# This script is a wrapper around the individual install scripts
# - located in /installer/runparts.d

if [ "$1" = "--unattended" ]; then
    shift
    export CONFIG_UNATTENDED=true
fi

if [ "$1" = "--timestamps" ]; then
    shift
    TIMESTAMPS=true
fi

runparts() {
    for i in /installer/runparts.d/*.sh; do
        if [ -x "$i" ]; then
            # shellcheck disable=SC2154
            # the variable is set outside this script
            echo "Starting script $script_prefix $i:"

            # shellcheck source=/dev/null
            # all to be checked by shellcheck separately
            . "$i"
        fi
    done
}

set -e

LOCKFILE=/installer/installer.lock
if [ -e "$LOCKFILE" ]; then
    echo "Install already in progress (lock file $LOCKFILE exists)"
    exit 1
fi
touch "$LOCKFILE"

if [ "$TIMESTAMPS" = "true" ]; then
    runparts | ts -s
else
    runparts
fi

rm "$LOCKFILE"

