#!/bin/sh
#
# Show the status page and optionally start the installer
#

# First, show the status page
HTOPRC=/etc/htoprc.big htop

if [ ! -x /installer/installer ]; then
    # dont prompt to run the installer if it does not exist
    exit
fi

if dialog \
    --timeout 120 \
    --backtitle "Manually run the Installer" \
    --title "Start system installation" \
    --defaultno \
    --yesno "WARNING: Starting the installation process will wipe the \
    contents of your hard drive.    Are you sure you wish to continue" \
    0 0; then
    # Only trigger the install if "OK" was pressed

    # TODO
    # - logging should be a feature of the installer, not the wrapper
    script -a -c /installer/installer /installer/install.log

    # not actually expected to exit, so pause to show any error messages
    echo Install exited, press enter

    # shellcheck disable=SC2034
    read -r throwaway
fi

